### ISSUE TITLE
pctl upgrade should default to latest version if no version is provided

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#260]
**What feature/behavior/change do you want?**

**Why do you want this feature?**

**Comment by Callisto13** [comment]
Thanks @sympatheticmoose 👍  My comment was a bit blunt, a quick reminder from a planning discussion 🙈 

> I would think we would want to encourage adoption of the latest updates

Yes definitely agree with that.

> I would expect most upgrade commands to grab latest unless I specify a version as a parameter.

There is a difference between _latest_ and _latest compatible_ version. In the case of upgrading, eg, a CLI tool, then upgrading to latest is nbd. But on a live system, or live-adjacent in the case of profiles, things can get messy and we would be relying on the goodwill of authors to ensure things can be moved forwards without conflicts. At that point we have to decide where the cut off would be.

Our main concern is when, for example, someone has `0.5.0` installed. They call `upgrade` and latest is `0.8.0`. That is quite a significant jump. In many situations like this you would say that they could only jump, say, 1 or 2 minor versions, or go through some patches first. (We could be smart and figure that out for them of course, but that would perhaps assume a rule of compatibility applied to all profiles which authors have to follow).

Obviously the risk for us is way lower, since we don't deploy anything live, so a botched upgrade is annoying more than anything else.

Our initial thought was to have a `--latest` flag or `latest` arg, so if users wanted to yolo it they could.

**Comment by Himangini** [comment]
@sympatheticmoose have we decided on this? shall we close this issue or proceed to implement the suggestion
> Our initial thought was to have a --latest flag or latest arg, so if users wanted to yolo it they could.
and then we can just learn/refine as we get more adoption?

**Comment by sympatheticmoose** [comment]
Up to y'all. I was happy with the suggested plan as stated :)

**Comment by aclevername** [comment]
Out in `0.9.0` @sympatheticmoose :smile:
