### ISSUE TITLE
Nginx profile replica count ignored after deployment

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/pctl#293]
**What were you trying to accomplish?**
Scale down the # of replicas for the nginx profile

**What happened?**

I committed a change to the configmap, replica-count: 1, the configmap is updated in the cluster however, the # of replicas didn't decrease
**How to reproduce it?**

Install the nginx profile, after it is running in the cluster, edit the configmap and change the replica count

**Logs**

**Anything else we need to know?**

I'm not certain this is a pctl issue - other than maybe the helmrelese should mount the configmap instead of just pulling values from it.  The mount should cause the helmrelease to be processed again.

**Versions**
`pctl version 0.7.0`

**Comment by aclevername** [comment]
Thanks for opening the issue @palemtnrider ! Yes this is a real pain/problem. We noticed this behaviour a while back. As you point out, this is more of a flux issue as the `helm-controller` doesn't reconcile the `HelmRelease` resource when a change to the config map occurs. See https://github.com/fluxcd/helm-controller/issues/42

I'm not sure what can be done on pctl side to fix this, perhaps some documentation. I recall @Skarlso mentioning some fix relating to kube watcher before? Can you provide some more context :smile: ?

**Comment by Skarlso** [comment]
Hi! :) 

Okay, so as Jake already described, the issue stems from the fact that flux is not watching this resource for changes and acting on it. PCTL can't do that either, because it doesn't have a controller to observe changes to kubernetes resources of course. There was a discussion of flux doing this, however, the consensus was, that since Flux already provides hooks which can be used by [kubewatch](https://github.com/bitnami-labs/kubewatch) and setting that up is not so hard; point it at the HelmRelease and point kubewatch at the ConfigMap on the input end, and at the webhook receiver on the output end and then flux should trigger a reconcile when there is a change on said resource.

This is a bit convoluted, but that's the reason for stalling on the flux part. Or rather de-prioritising this.

**Comment by aclevername** [comment]
@bigkevmcd is going to sync up with flux folks to see if we can be of any help in progressing the work on there end
