### ISSUE TITLE
[Spike] Expose Profiles API

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/pctl#308]
**What feature/behavior/change do you want?**
The profiles "API" should be available for importing into other projects.

**Why do you want this feature?**
As we integrate profiles into other components, we want to be able to use the same logic as `ptcl` uses to manage profiles in repositories.

To do this, we should adopt an architecture that makes this easier, fore example `cmd/pctl/add.go` contains the logic to add profiles to a repository, this should be more easily callable from other projects.

The role of the `cmd/pctl` code should be to get in data, and pass it through to the core logic to execute.

**Comment by Himangini** [comment]
Needs a spike to flesh out the details for this work.

**Comment by Skarlso** [comment]
The attached PR explored refactoring some of things we do in the CLI region. I exposed the aforementioned AddProfile but it turns out that that's pretty much we can sanely expose from what the CLIs are doing and still add some value to them.

The rest of the CLI stuff is using little logic in how in constructs and uses functionality available in the `pkg` section for outside importing. Most of the things it does is basically validation on the parameters and such.

Never the less, I believe that the PR does add some value, if nothing else, I did refactor some pieces of code which got a bit simpler because of that and the `AddProfiles` function IS exported reducing duplication for Team Plutonium.

The architecture I eventually went with is having another package called `api` which holds things that the CLI calls and can be a high level calling from outside of PCTL by other users. I found that this package has some relevance in the Go community as a whole and thus was a good choice to boot. I explored putting some functionality inside `pkg` but that doesn't signify the usage structure as much and looses focal point ( entry point ) to PCTL. While the separate `api` package signifies usage better by saying, hello, import and use me.

Feel free to object / suggest different options. :)

**Comment by Skarlso** [comment]
If the attached PR is acceptable, I'll update it with testing and make it an official change.

**Comment by Skarlso** [comment]
Expanded with unit tests.

**Comment by Skarlso** [comment]
What is the desired outcome of this ticket now? What should the Wego peeps expect?

**Comment by Skarlso** [comment]
So the spike was made, I consider this ticket closed.
