### ISSUE TITLE
Command to install Profiles controller and CRD

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#5]
```sh
pctl install/bootstrap/prepare/seed # whatever
```

should install ProfileSub, ProfileCatalogSource and whatever else in my cluster

**Comment by aclevername** [comment]
just the CRDs doesn't seem that useful, the whole `profiles` controller deployment + CRDs sounds useful, mirroring `flux bootstrap`

**Comment by Skarlso** [comment]
Further things for prepare.....

- [ ] we need to give the manifests a namepsace. they can’t be in system So that’s a default I’ll add to all kustomize files. ( flux also does this )
- [ ] add missing rbac to manifests.tar.gz
- [ ] create a latest tag for the profiles-controller so the manifest installation can work right off the bat without the need to give a version
- [ ] deal with the kube-rbac-proxy sidecar which is created by our default kustomize build

**Comment by Callisto13** [comment]
@Skarlso is this ticket closable or are there still bits to do?
